name: strv_app_implemented
description: STRV workshop application
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  # Core
  flutter:
    sdk: flutter

  fimber: ^0.4.4

  # Bloc Architecture
  flutter_bloc: ^6.1.1
  equatable: ^1.2.5

  # Network Packages
  http: ^0.12.2
  http_interceptor: ^0.3.3
  provider: ^4.3.3

  # Image handling
  cached_network_image: ^2.5.0
  photo_view: ^0.10.3

  # General build dependency
  # To change launcher icon
  flutter_launcher_icons: ^0.8.1

  # To change launcher name
  flutter_launcher_name: ^0.0.1

  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/app.png

flutter_launcher_name:
  name: "S-XKCD"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app.png"
  adaptive_icon_background: "#111517"
  adaptive_icon_foreground: "assets/images/app_icon_foreground.png"